version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - JWT_SECRET=${JWT_SECRET:-default-secret}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SECURITY_LOG_LEVEL=${SECURITY_LOG_LEVEL:-INFO}
      - ROOT_LOG_LEVEL=${ROOT_LOG_LEVEL:-INFO}
    volumes:
      - h2-data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  h2-data: