spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
data.init: true