spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME:testdb};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create-drop}
    defer-datasource-initialization: ${DEFER_DATASOURCE_INITIALIZATION:true}
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

logging:
  level:
    com.furkan.digitalWallet: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.springframework.jdbc.datasource.init: DEBUG
    root: ${ROOT_LOG_LEVEL:INFO}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:default-secret}
  expiration: 3600

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}

data.init: ${DATA_INIT:true}
