spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    com.furkan.digitalWallet: DEBUG
server:
  port: 8080
jwt:
  secret: X9juUahlqib1eNF1hkNlwRV4J2jklpQK6UuYWxmlfhLFA0qzChTjtjzH7O50ffEwU46BGXOLXf+1CtByumhatBL/FHF41dxazOgwHaO/L8tkpAmLBSkM78v3jHE8xHW6l6Vxar5O4tUYTheK+TxuYN7oLU7cz1w6LjhDl9FACv9BHMVdmPXFMXS/KYa2Je+QDLhqXlHD0//8iMK0e+89hj6rhIuVsVYpQ==
  expiration: 3600
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  packages-to-scan: com.furkan.digitalWallet.controller
  paths-to-match: /**

data.init: true